"""Create review_jobs table

Revision ID: bfcbbc93836f
Revises: c7d9e1f3a5b2
Create Date: 2026-09-02 00:24:50.932430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfcbbc93836f'
down_revision: Union[str, Sequence[str], None] = 'c7d9e1f3a5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', 'pull_request_id', 'head_sha', name='uq_review_job_inst_pr_sha')
    )
    op.create_index(op.f('ix_review_jobs_id'), 'review_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_review_jobs_installation_id'), 'review_jobs', ['installation_id'], unique=False)
    op.create_index(op.f('ix_review_jobs_pull_request_id'), 'review_jobs', ['pull_request_id'], unique=False)
    op.create_index('ix_review_jobs_status_available_at', 'review_jobs', ['status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_jobs_status_available_at', table_name='review_jobs')
    op.drop_index(op.f('ix_review_jobs_pull_request_id'), table_name='review_jobs')
    op.drop_index(op.f('ix_review_jobs_installation_id'), table_name='review_jobs')
    op.drop_index(op.f('ix_review_jobs_id'), table_name='review_jobs')
    op.drop_table('review_jobs')
    # ### end Alembic commands ###
