"""add installation_id to repositories

Revision ID: f289a7108fff
Revises: f7fba7dbe505
Create Date: 2026-07-18 18:06:00.463662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f289a7108fff'
down_revision: Union[str, Sequence[str], None] = 'f7fba7dbe505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('installation_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'installation_id')
    # ### end Alembic commands ###
